
-- Example: 
-- Vehicles[2].name = Mancini Cavallo 1001
-- Vehicles[2].isDLC = false

local IsDLC = true
local IsNotDLC = false

local AddVehicle = function(modelId , name , IsDLC)
	
	local vehicle = {}
	vehicle.name = name
	vehicle.isDLC = IsDLC
	Vehicles[modelId] = vehicle
	
end

AddVehicle(1 , "Dongtai Agriboss 35" , IsNotDLC)
AddVehicle(2 , "Mancini Cavallo 1001" , IsNotDLC)
AddVehicle(4 , "Kenwall Heavy Rescue" , IsNotDLC)
AddVehicle(7 , "Poloma Renegade" , IsNotDLC)
AddVehicle(8 , "Columbi Excelsior" , IsNotDLC)
AddVehicle(9 , "Tuk-Tuk Rickshaw" , IsNotDLC)
AddVehicle(10 , "Saas PP12 Hogg" , IsNotDLC)
AddVehicle(11 , "Shimuzu Tracline" , IsNotDLC)
AddVehicle(12 , "Vanderbildt LeisureLiner" , IsNotDLC)
AddVehicle(13 , "Stinger Dunebug 84" , IsNotDLC)
AddVehicle(15 , "Sakura Aquila Space" , IsNotDLC)
AddVehicle(18 , "SV-1003 Raider" , IsNotDLC)
AddVehicle(20 , "Monster Truck" , IsDLC)
AddVehicle(21 , "Hamaya Cougar 600" , IsNotDLC)
AddVehicle(22 , "Tuk-Tuk Laa" , IsNotDLC)
AddVehicle(23 , "Chevalier Liner SB" , IsNotDLC)
AddVehicle(26 , "Chevalier Traveller SD" , IsNotDLC)
AddVehicle(29 , "Sakura Aquila City" , IsNotDLC)
AddVehicle(31 , "URGA-9380" , IsNotDLC)
AddVehicle(32 , "Mosca 2000" , IsNotDLC)
AddVehicle(33 , "Chevalier Piazza IX" , IsNotDLC)
AddVehicle(35 , "Garret Traver-Z" , IsNotDLC)
AddVehicle(36 , "Shimuzu Tracline" , IsNotDLC)
AddVehicle(40 , "Fengding EC14FD2" , IsNotDLC)
AddVehicle(41 , "Niseco Coastal D22" , IsNotDLC)
AddVehicle(42 , "Niseco Tusker P246" , IsNotDLC)
AddVehicle(43 , "Hamaya GSY650" , IsNotDLC)
AddVehicle(44 , "Hamaya Oldman" , IsNotDLC)
AddVehicle(46 , "MV V880" , IsNotDLC)
AddVehicle(47 , "Schulz Virginia" , IsNotDLC)
AddVehicle(48 , "Maddox FVA 45" , IsNotDLC)
AddVehicle(49 , "Niseco Tusker D18" , IsNotDLC)
AddVehicle(52 , "Saas PP12 Hogg" , IsNotDLC)
AddVehicle(54 , "Boyd Fireflame 544" , IsNotDLC)
AddVehicle(55 , "Sakura Aquila Metro ST" , IsNotDLC)
AddVehicle(56 , "GV-104 Razorback" , IsNotDLC)
AddVehicle(58 , "Chevalier Classic" , IsDLC)
AddVehicle(60 , "Vaultier Patrolman" , IsNotDLC)
AddVehicle(61 , "Makoto MZ 260X" , IsNotDLC)
AddVehicle(63 , "Chevalier Traveller SC" , IsNotDLC)
AddVehicle(66 , "Dinggong 134D" , IsNotDLC)
AddVehicle(68 , "Chevalier Traveller SX" , IsNotDLC)
AddVehicle(70 , "Sakura Aguila Forte" , IsNotDLC)
AddVehicle(71 , "Niseco Tusker G216" , IsNotDLC)
AddVehicle(72 , "Chepachet PVD" , IsNotDLC)
AddVehicle(73 , "Chevalier Express HT" , IsNotDLC)
AddVehicle(74 , "Hamaya 1300 Elite Cruiser" , IsNotDLC)
AddVehicle(75 , "Tuk Tuk Boom Boom" , IsDLC)
AddVehicle(76 , "SAAS PP30 Ox" , IsNotDLC)
AddVehicle(77 , "Hedge Wildchild" , IsNotDLC)
AddVehicle(78 , "Civadier 999" , IsNotDLC)
AddVehicle(79 , "Pocumtuck Nomad" , IsNotDLC)
AddVehicle(82 , "Chevalier Ice Breaker" , IsDLC)
AddVehicle(83 , "Mosca 125 Performance" , IsNotDLC)
AddVehicle(84 , "Marten Storm III" , IsNotDLC)
AddVehicle(86 , "Dalton N90" , IsNotDLC)
AddVehicle(87 , "Wilforce Trekstar" , IsNotDLC)
AddVehicle(89 , "Hamaya Y250S" , IsNotDLC)
AddVehicle(90 , "Makoto MZ 250" , IsNotDLC)
AddVehicle(91 , "Titus ZJ" , IsNotDLC)

AddVehicle(5 , "Pattani Gluay" , IsNotDLC)
AddVehicle(6 , "Orque Grandois 21TT" , IsNotDLC)
AddVehicle(16 , "YP-107 Phoenix" , IsNotDLC)
AddVehicle(19 , "Orque Living 42T" , IsNotDLC)
AddVehicle(25 , "Trat Tang-mo" , IsNotDLC)
AddVehicle(27 , "SnakeHead T20" , IsNotDLC)
AddVehicle(28 , "TextE Charteu 52CT" , IsNotDLC)
AddVehicle(38 , "Kuang Sunrise" , IsNotDLC)
AddVehicle(45 , "Orque Bon Ton 71FT" , IsNotDLC)
AddVehicle(50 , "Zhejiang 6903" , IsNotDLC)
AddVehicle(53 , "Agency Hovercraft" , IsDLC)
AddVehicle(69 , "Winstons Amen 69" , IsNotDLC)
AddVehicle(80 , "Frisco Catshark S-38" , IsNotDLC)
AddVehicle(88 , "MTA Powerrun 77" , IsNotDLC)

AddVehicle(3 , "Rowlinson K22" , IsNotDLC)
AddVehicle(14 , "Mullen Skeeter Eagle" , IsNotDLC)
AddVehicle(24 , "F-33 DragonFly Jet Fighter" , IsDLC)
AddVehicle(30 , "Si-47 Leopard" , IsNotDLC)
AddVehicle(34 , "G9 Eclipse" , IsNotDLC)
AddVehicle(37 , "Sivirkin 15 Havoc" , IsNotDLC)
AddVehicle(39 , "Aeroliner 474" , IsNotDLC)
AddVehicle(51 , "Cassius 192" , IsNotDLC)
AddVehicle(57 , "Sivirkin 15 Havoc" , IsNotDLC)
AddVehicle(59 , "Peek Airhawk 225" , IsNotDLC)
AddVehicle(62 , "UH-10 Chippewa" , IsNotDLC)
AddVehicle(64 , "AH-33 Topachula" , IsNotDLC)
AddVehicle(65 , "H-62 Quapaw" , IsNotDLC)
AddVehicle(67 , "Mullen Skeeter Hawk" , IsNotDLC)
AddVehicle(81 , "Pell Silverbolt 6" , IsNotDLC)
AddVehicle(85 , "Bering I-86DP" , IsNotDLC)
